project:
  type: website
  output-dir: docs

website:
  title: "Felipe Fontana Vieira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: solar
    css: styles.css
    toc: true

editor: visual

