---
title: "Curriculum vitae"
---

## Education

-   2024-*present* \| PhD Researcher in Statistical Data Analysis, Department of Data-Analysis, Faculty of Psychology and Educational Sciences, Ghent University.

-   2023-2026 \| Subsequent Master's degree in Statistical Data Analysis (M.Sc.), Faculty of Science, Ghent University. *Cum Laude*

-   2021-2023 \| Master's degree in Psychology (Theory and Research) (M.Sc.), Faculty of Psychology and Educational Sciences, KU Leuven. *Cum Laude*

-   2018-2021 \| Bachelor's degree in Psychology, Faculty of Psychology and Educational Sciences, University of Coimbra.

## Work and Research Experience

-   2024-*present* \| PhD Researcher in Statistical Data Analysis, Department of Data-Analysis, Faculty of Psychology and Educational Sciences, Ghent University.

-   November 2023 - May 2024 \| Part-time Desk Researcher, Verian Group Belgium.

-   May 2023 - September 2023 \| Part-time Research Assistant, Methods, Individual and Cultural Differences, Affect and Social Behavior (OE), KU Leuven.

-   August 2022 — June 2023 \| Part-time Research Assistant, Center for Social and Cultural Psychology (CSCP), KU Leuven.

-   September 2022 — March 2023 \| Full-time Research Intern, Center for Social and Cultural Psychology (CSCP), KU Leuven.

-   February 2021 — June 2021 \| Research Project TEACHmi, Faculty of Psychology and Educational Sciences, University of Coimbra.

## Poster Presentations and Talks

-   **Vieira, F. F.** (Presenting Author), Slupphaug, K. S., & Rosseel, Y. (2026). Evaluating Local Structural-After-Measurement (LSAM) and Traditional Approaches for the Estimation of Complex Nonlinear Effects Among Latent Variables. Oral Presentation at the SEM Working Group Meeting, organized by IBE and IFiS PAN, Warsaw, Poland, April 15th-17th, 2026.

-   **Vieira, F. F.** (Presenting Author), & Rosseel, Y. (2025). Nonlinear Effects in Structural Equations With Latent Variables. Oral Presentation at the European Congress of Methodology, University of La Laguna, Tenerife, Spain, July 23rd-25th, 2025.

-   **Vieira, F. F.** (2025). A Gentle Introduction to Structural Equation Modeling (Invited Talk, Hosted by the Quantitative Group). Faculty of Education, Cambridge University, February 10th, 2025.

-   **Vieira, F. F.** (Presenting Author), Jasini, A., Tekin, E. A., & Mesquita, B. (2023). Majorities’ Emotions Acculturate too: The Role of Intergroup Friendships and Clarity of Minority Emotion Norms. Poster Presented at the ASPO 2023, Utrecht, Netherlands, April 20th-21st, 2023.

-   Costantino, A., Van Hove, L. (Presenting Author), **Vieira, F. F.**, & Op de Beeck, H. (2023). Does Expertise Affect the Geometry of Object Representations in the Brain? Poster Presented at the BAPS 2023, Mons, Belgium, May 25th-26th, 2023.

## Publications

### Peer-Reviewed Articles

-   Bartoš, F., Sarafoglou, A., Godmann, H. R., Sahrani, A., Klein Leunk, D., Gui, P. Y., ... **Vieira, F. F.**, et al. (2025). Fair coins tend to land on the same side they started: Evidence from 350,757 flips. *Journal of the American Statistical Association*, *120*(552), 2118–2127.

-   Jasini, A., Tekin, E. A., **Vieira, F. F.**, & Mesquita, B. (2024). Majorities' emotions acculturate too: The role of intergroup friendships and clarity of minority emotion norms. *International Journal of Intercultural Relations*, *98*, 101923.

### Preprints and Working Papers

-   **Vieira, F. F.**, Slupphaug, K., & Rosseel, Y. (2026, May 15). *Evaluating Local Structural-After-Measurement (LSAM) and Traditional Approaches for the Estimation of Complex Nonlinear Effects Among Latent Variables*. Retrieved from [osf.io/preprints/psyarxiv/xk8um_v3](https://osf.io/preprints/psyarxiv/xk8um_v3). Accepted for publication in *Psychological Methods*.

-   Costantino, A. I., Platonov, A., **Vieira, F. F.**, Van Hove, E., Bilalić, M., et al. (2025). *Low-dimensional and optimised representations of high-level information in the expert brain* [Preprint]. bioRxiv. [https://doi.org/10.1101/2025.11.12.688012](https://doi.org/10.1101/2025.11.12.688012). Accepted for publication in *Nature Communications*.

-   **Vieira, F. F.**, Geller, J., & Rodrigues, B. (2026, January 28). *Why Risk it, When You Can {rix} it: A Tutorial for Computational Reproducibility Focused on Simulation Studies*. Retrieved from [osf.io/preprints/psyarxiv/a3e8v_v1](https://osf.io/preprints/psyarxiv/a3e8v_v1)

-   **Vieira, F. F.**, & Rosseel, Y. (2026). *Latent Variables Moderated Mediation Using Correct and Misspecified Models*. [https://doi.org/10.5281/zenodo.20703258](https://doi.org/10.5281/zenodo.20703258)

-   Justus, V. L., & **Vieira, F. F.** (2026). *Covariate-adjusted statistical dependence representation through partial copulas: Bounds and new insights* [Preprint]. arXiv. [https://arxiv.org/abs/2603.10941](https://arxiv.org/abs/2603.10941)

-   Hartmann, H., Azevedo, F., Röseler, L., Wallrich, L., Aldoh, A., Elsherif, M., Liu, M., ... **Vieira, F. F.**, et al. (2025). *Tracking and mainstreaming replications in the social, cognitive, and behavioral sciences* [Preprint]. OSF. [https://doi.org/10.31222/osf.io/ad2w6_v5](https://doi.org/10.31222/osf.io/ad2w6_v5)

-   Janý, M., Xiao, Q., Yeung, S., Ben-Shachar, M. S., Caldwell, A., Cousineau, D., ... **Vieira, F. F.**, et al. (2024). *Guide to effect sizes and confidence intervals*. OSF. [https://doi.org/10.17605/OSF.IO/D8C4G](https://doi.org/10.17605/OSF.IO/D8C4G)
